### ISSUE TITLE
Test sketch

### ISSUE THREAD

**Issue by Sukalo0290** [RobTillaart/DHTNew#78] opened 2022-07-10 10:52 UTC
Do you happen to have a test sketch to try? Arduino Esp32

**Comment by RobTillaart** [comment] 2022-07-10 10:57
All examples should work on ESP32. 
You just need to change the datapin in the examples.

**Comment by Sukalo0290** [comment] 2022-07-10 11:08
Thanks, not going to lie I didn't look in there properly. I assume the dhtnew_test would be the best one to try?

**Comment by RobTillaart** [comment] 2022-07-10 11:33
What is the best is subjective.

If you take 20 minutes you can quickly go through all examples. Just read them and try to understand what happens.  You will note the similarities between the code. It might even be that one of the examples is very close to your needs/ideas.

**Comment by RobTillaart** [comment] 2022-07-10 17:58
If the issue is solved you may close it

**Closed** 2022-07-11 15:43 UTC
Labels: question
